'use strict';
const state={mode:'normal',lux:320,target:320,darkSince:null,samples:[],lastEvent:'Khởi tạo mô phỏng · cảm biến sẵn sàng'};
const luxValue=document.querySelector('#luxValue'),luxMeter=document.querySelector('#luxMeter'),modeChip=document.querySelector('#modeChip'),liveCopy=document.querySelector('#liveCopy'),demoNarrative=document.querySelector('#demoNarrative'),darkTimer=document.querySelector('#darkTimer'),darkAlert=document.querySelector('#darkAlert'),toast=document.querySelector('#toast'),chartLine=document.querySelector('#chartLine'),chartArea=document.querySelector('#chartArea'),proofModal=document.querySelector('#proofModal'),proofRows=document.querySelector('#proofRows'),proofCount=document.querySelector('#proofCount');
document.querySelector('.live-card').insertAdjacentHTML('afterend','<section class="telemetry-strip" aria-label="Chi tiết phép đo"><div class="telemetry-item"><span>Chu kỳ mẫu</span><strong>2 giây</strong></div><div class="telemetry-item"><span>Trung bình trượt</span><strong id="rollingAvg">320 lux</strong></div><div class="telemetry-item"><span>Min · Max</span><strong id="rangeValue">320 · 320</strong></div><div class="telemetry-item"><span>Chất lượng tín hiệu</span><strong id="signalQuality">Ổn định</strong></div><div class="event-log" id="eventLog"><i></i><strong>Sự kiện:</strong> <span id="eventText">Khởi tạo mô phỏng · cảm biến sẵn sàng</span></div></section>');
const rollingAvg=document.querySelector('#rollingAvg'),rangeValue=document.querySelector('#rangeValue'),signalQuality=document.querySelector('#signalQuality'),eventLog=document.querySelector('#eventLog'),eventText=document.querySelector('#eventText');
function statusFor(lux){return lux<30?'DARK':lux<180?'DIM':'NORMAL'}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),1800)}
function setEvent(message,warning=false){state.lastEvent=message;eventText.textContent=message;eventLog.classList.toggle('warning',warning)}
function renderChart(){const values=state.samples.slice(-18).map(item=>item.lux);if(values.length<2)return;const points=values.map((value,index)=>{const x=index/(values.length-1)*640;const y=165-(Math.min(360,value)/360)*135;return `${x.toFixed(1)},${y.toFixed(1)}`});chartLine.setAttribute('d','M'+points.join(' L'));chartArea.setAttribute('d','M'+points.join(' L')+' L640,190 L0,190 Z')}
function recordSample(){state.samples.push({time:new Date(),lux:Math.round(state.lux),status:statusFor(state.lux)});if(state.samples.length>120)state.samples.shift();renderChart();renderTelemetry()}
function renderTelemetry(){const values=state.samples.map(item=>item.lux);if(!values.length)return;const average=Math.round(values.slice(-10).reduce((sum,value)=>sum+value,0)/Math.min(10,values.length));rollingAvg.textContent=average+' lux';rangeValue.textContent=Math.min(...values)+' · '+Math.max(...values);signalQuality.textContent=state.mode==='off'?'Đang theo dõi':'Ổn định'}
function render(){const lux=Math.round(state.lux),status=statusFor(lux);luxValue.textContent=lux;luxMeter.style.width=Math.min(100,lux/4)+'%';modeChip.textContent=status;modeChip.className='mode-chip '+status.toLowerCase();liveCopy.textContent=status==='NORMAL'?'Ánh sáng ổn định, mô phỏng mức phù hợp để học tập.':status==='DIM'?'Ánh sáng đang giảm. Hãy quan sát tiếp hoặc bật thêm đèn.':'Môi trường thiếu sáng. Hệ thống đang theo dõi thời gian kéo dài.';if(status==='DARK'){if(!state.darkSince){state.darkSince=Date.now();setEvent('Lux < 30 · bắt đầu bộ đếm cảnh báo',true)}const seconds=Math.min(3,Math.floor((Date.now()-state.darkSince)/1000));darkTimer.textContent=`Đang theo dõi thiếu sáng: ${seconds}/3 giây`;darkAlert.hidden=Date.now()-state.darkSince<3000;if(!darkAlert.hidden)setEvent('Cảnh báo kích hoạt · thiếu sáng liên tục 3 giây',true)}else{state.darkSince=null;darkTimer.textContent='Chưa có cảnh báo';darkAlert.hidden=true}}
function setLight(mode){state.mode=mode;state.target=mode==='off'?25:320;document.querySelectorAll('[data-light]').forEach(button=>button.classList.toggle('active',button.dataset.light===mode));demoNarrative.textContent=mode==='off'?'Đèn đã tắt · lux đang giảm về khoảng 20–30.':'Đèn đang bật · lux sẽ trở lại khoảng 300.';if(mode!=='off'){state.darkSince=null;darkAlert.hidden=true;setEvent('Nguồn sáng trở lại · theo dõi lux tăng dần')}else setEvent('Lệnh tắt đèn · chờ tín hiệu giảm',true);showToast(mode==='off'?'Đang mô phỏng tắt đèn':'Đang mô phỏng bật đèn')}
document.querySelectorAll('[data-light]').forEach(button=>button.addEventListener('click',()=>setLight(button.dataset.light)));
setInterval(()=>{const noise=(Math.random()-.5)*(state.mode==='off'?7:34);const desired=Math.max(0,state.target+noise);state.lux+=(desired-state.lux)*.1;if(Math.abs(state.target-state.lux)<.4)state.lux=state.target;render()},120);setInterval(recordSample,2000);recordSample();render();
function refreshProof(){proofCount.textContent=state.samples.length;proofRows.innerHTML=state.samples.slice(-8).reverse().map(item=>`<tr><td>${item.time.toLocaleTimeString('vi-VN',{hour12:false})}</td><td>${item.lux}</td><td>${item.status}</td></tr>`).join('')||'<tr><td colspan="3">Chưa có mẫu</td></tr>'}
function openProof(){refreshProof();proofModal.hidden=false}document.querySelector('#openProof').addEventListener('click',openProof);document.querySelector('#closeProof').addEventListener('click',()=>proofModal.hidden=true);proofModal.addEventListener('click',event=>{if(event.target.hasAttribute('data-close-proof'))proofModal.hidden=true});document.addEventListener('keydown',event=>{if(event.key==='Escape')proofModal.hidden=true});document.querySelector('#downloadCsv').addEventListener('click',()=>{const rows=['timestamp,lux,status',...state.samples.map(item=>`${item.time.toISOString()},${item.lux},${item.status}`)];const url=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='bh1750-demo-samples.csv';link.click();URL.revokeObjectURL(url);showToast('Đã tải CSV mẫu')});
